# Generated by Django 5.1.3 on 2025-01-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'feature_feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_product_features',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FeatureValue',
        ),
        migrations.AlterModelTable(
            name='externalproduct',
            table='product_product',
        ),
    ]
