# Generated by Django 5.1.3 on 2025-01-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_externalcategory_externalfeature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_productimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'product_product_features',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='externalfeature',
            table='product_feature',
        ),
        migrations.AlterModelTable(
            name='externalfeaturevalue',
            table='product_featurevalue',
        ),
    ]
